#!/bin/bash

DISK_THRESHOLD=1

DISK_USAGE=($(df -HT | awk 'NR>1 {gsub("%","",$6); print $7":"$6}'))


for disk in "${DISK_USAGE[@]}"
do
  path=$(echo "$disk" | cut -d ":" -f1)
  usage=$(echo "$disk" | cut -d ":" -f2)  
  MSG=""
    if [ "$usage" -gt "$DISK_THRESHOLD" ]
    then
    MSG=" echo "Warning: $path is using $usage% of its space"
    fi
done